Repository keras-team/tf-keras, pull requests merged in 2024-02, with the labels that each got.

#739 Add Python 3.12 tag to Setup
  oss_setup.py
Labels: size:XS

#740 Add Python 3.12 tag
  tf_keras/tools/pip_package/setup.py
Labels: size:XS

#750 Cherry pick r2.16
  oss_setup.py
  pip_build.py
  tf_keras/__init__.py
  tf_keras/tools/pip_package/setup.py
Labels: size:S

#721 Minor change to unit validation in tf.keras.layers.Dense
  tf_keras/layers/core/dense.py
Labels: ready to pull, size:M

#755 When pinning TF Version, allow for various versions of RC.
  oss_setup.py
Labels: size:XS
